### PR TITLE
Add support for v0.8.0

### PR DESCRIPTION
**Pull request by rkalis**
- Update Antlr grammar
- Add token properties to inputs and outputs
- Remove 'OutputX' in favour of 'LockingBytecodeX'
- Remove 'Compilation' functionality due to ESM incompatibilties
- Small fixes (highlight '*' and '0x' in code)
- Update examples

### CODE REVIEW

**Comment by rkalis** [comment]
Hey @nathanielCherian, I just added support for CashScript v0.8.0 features to the VSCode extension. Would love it if you could take a look and merge + publish it if you have the time!

**Comment by nathanielCherian** [comment]
Looks good! Thanks for doing this and sorry for the earlier unresponsiveness.

**Comment by nathanielCherian** [comment]
Should be up now!

**Comment by rkalis** [comment]
No worries at all, and thanks for publishing it! If you ever figure out a way to re-enable the Compilation feature despite ESM incompatibilities, that would be awesome, but as far as we could see there's no way to do so.

**Comment by nathanielCherian** [comment]
Of course! That's unfortunate but I'll look into it.

**Pull request merged**
